SELECT 
    T.TABLE_CATALOG AS [catalog],
    T.TABLE_SCHEMA AS [schema],
    T.TABLE_NAME AS [name],
    T.TABLE_TYPE AS [type]
    FROM INFORMATION_SCHEMA.TABLES t
    ORDER BY t.TABLE_CATALOG, t.TABLE_SCHEMA, t.TABLE_NAME